language: java
env:
- DOCKER_HOST=unix:///var/run/docker.sock

sudo: required

services:
  - docker

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report coveralls:report
  - mvn clean test saga:coverage coveralls:report
  - mvn clean test saga:coverage cobertura:cobertura coveralls:report